query GET_USER_BY_ID($id: ID!) {
  getUserById(id: $id) {
    id
    name
    email
    age
    paymentMethod {
      id
      last4
      expMonth
      expYear
    }
  }
}

query GET_USERS {
  getUsers {
    id
    name
    email
    age
  }
}
